# Generated by Django 3.1.7 on 2021-02-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acerto_passe_curto', models.IntegerField(verbose_name='Short_pass')),
                ('acerto_passe_longo', models.IntegerField(verbose_name='Long_pass')),
                ('gols', models.IntegerField(verbose_name='Gols')),
                ('desarmes', models.IntegerField(verbose_name='Desarmes')),
                ('defesas', models.IntegerField(verbose_name='Defesas')),
                ('passes_gol', models.IntegerField(verbose_name='Pass_gol')),
                ('faltas', models.IntegerField(verbose_name='Faltas')),
                ('cartao_amarelo', models.IntegerField(verbose_name='Yellow_card')),
                ('cartao_vermelho', models.IntegerField(verbose_name='Red_card')),
                ('data', models.DateField(verbose_name='Data')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.jogador')),
            ],
        ),
    ]
