# Generated by Django 3.1.7 on 2021-02-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='acerto_passe_curto',
            field=models.IntegerField(default=0, verbose_name='Short_pass'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='acerto_passe_longo',
            field=models.IntegerField(default=0, verbose_name='Long_pass'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='cartao_amarelo',
            field=models.IntegerField(default=0, verbose_name='Yellow_card'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='cartao_vermelho',
            field=models.IntegerField(default=0, verbose_name='Red_card'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='defesas',
            field=models.IntegerField(default=0, verbose_name='Defesas'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='desarmes',
            field=models.IntegerField(default=0, verbose_name='Desarmes'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='faltas',
            field=models.IntegerField(default=0, verbose_name='Faltas'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='gols',
            field=models.IntegerField(default=0, verbose_name='Gols'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='passes_gol',
            field=models.IntegerField(default=0, verbose_name='Pass_gol'),
        ),
    ]
