# Generated by Django 3.1.7 on 2021-02-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('posicao', models.CharField(choices=[('La', 'Lateral Direito'), ('Ata_d', 'Atacante Direita'), ('Vm', 'Segundo Volante'), ('Le', 'Lateral Esquerdo'), ('Md', 'Meia Direita'), ('Mc', 'Meia Central'), ('Ce', 'Centroavante'), ('Ata_e', 'Atacante Esquerda'), ('Ze', 'Zagueiro Esquerdo'), ('V', 'Primeiro Volante'), ('Zd', 'Zagueiro Direito'), ('Go', 'Goleiro'), ('Me', 'Meia Esquerda')], default='Goleiro', max_length=17, verbose_name='Posicao')),
                ('posicao_opcao', models.CharField(choices=[('La', 'Lateral Direito'), ('Ata_d', 'Atacante Direita'), ('Vm', 'Segundo Volante'), ('Le', 'Lateral Esquerdo'), ('Md', 'Meia Direita'), ('Mc', 'Meia Central'), ('Ce', 'Centroavante'), ('Ata_e', 'Atacante Esquerda'), ('Ze', 'Zagueiro Esquerdo'), ('V', 'Primeiro Volante'), ('Zd', 'Zagueiro Direito'), ('Go', 'Goleiro'), ('Me', 'Meia Esquerda')], default='Goleiro', max_length=17, verbose_name='Posicao_opcao')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('lesoes', models.TextField(verbose_name='Lesões')),
                ('foto', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
