# Generated by Django 3.1.7 on 2021-02-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('Ze', 'Zagueiro Esquerdo'), ('Zd', 'Zagueiro Direito'), ('La', 'Lateral Direito'), ('Vm', 'Segundo Volante'), ('V', 'Primeiro Volante'), ('Ata_d', 'Atacante Direita'), ('Le', 'Lateral Esquerdo'), ('Ata_e', 'Atacante Esquerda'), ('Md', 'Meia Direita'), ('Me', 'Meia Esquerda'), ('Mc', 'Meia Central'), ('Go', 'Goleiro'), ('Ce', 'Centroavante')], default='Goleiro', max_length=17, verbose_name='Posicao'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao_opcao',
            field=models.CharField(blank=True, choices=[('Ze', 'Zagueiro Esquerdo'), ('Zd', 'Zagueiro Direito'), ('La', 'Lateral Direito'), ('Vm', 'Segundo Volante'), ('V', 'Primeiro Volante'), ('Ata_d', 'Atacante Direita'), ('Le', 'Lateral Esquerdo'), ('Ata_e', 'Atacante Esquerda'), ('Md', 'Meia Direita'), ('Me', 'Meia Esquerda'), ('Mc', 'Meia Central'), ('Go', 'Goleiro'), ('Ce', 'Centroavante')], max_length=17, null=True, verbose_name='Posicao_opcao'),
        ),
    ]
