# Generated by Django 3.1.7 on 2021-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20210220_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='lesoes',
            field=models.TextField(blank=True, null=True, verbose_name='Lesões'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('Mc', 'Meia Central'), ('Zd', 'Zagueiro Direito'), ('V', 'Primeiro Volante'), ('Md', 'Meia Direita'), ('Ata_e', 'Atacante Esquerda'), ('Ze', 'Zagueiro Esquerdo'), ('La', 'Lateral Direito'), ('Me', 'Meia Esquerda'), ('Ce', 'Centroavante'), ('Vm', 'Segundo Volante'), ('Ata_d', 'Atacante Direita'), ('Le', 'Lateral Esquerdo'), ('Go', 'Goleiro')], default='Goleiro', max_length=17, verbose_name='Posicao'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao_opcao',
            field=models.CharField(blank=True, choices=[('Mc', 'Meia Central'), ('Zd', 'Zagueiro Direito'), ('V', 'Primeiro Volante'), ('Md', 'Meia Direita'), ('Ata_e', 'Atacante Esquerda'), ('Ze', 'Zagueiro Esquerdo'), ('La', 'Lateral Direito'), ('Me', 'Meia Esquerda'), ('Ce', 'Centroavante'), ('Vm', 'Segundo Volante'), ('Ata_d', 'Atacante Direita'), ('Le', 'Lateral Esquerdo'), ('Go', 'Goleiro')], max_length=17, null=True, verbose_name='Posicao_opcao'),
        ),
    ]
