# Generated by Django 3.1.7 on 2021-02-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20210220_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('Ze', 'Zagueiro Esquerdo'), ('V', 'Primeiro Volante'), ('Ce', 'Centroavante'), ('Me', 'Meia Esquerda'), ('Md', 'Meia Direita'), ('Le', 'Lateral Esquerdo'), ('La', 'Lateral Direito'), ('Go', 'Goleiro'), ('Vm', 'Segundo Volante'), ('Mc', 'Meia Central'), ('Zd', 'Zagueiro Direito'), ('Ata_e', 'Atacante Esquerda'), ('Ata_d', 'Atacante Direita')], default='Goleiro', max_length=17, verbose_name='Posicao'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao_opcao',
            field=models.CharField(blank=True, choices=[('Ze', 'Zagueiro Esquerdo'), ('V', 'Primeiro Volante'), ('Ce', 'Centroavante'), ('Me', 'Meia Esquerda'), ('Md', 'Meia Direita'), ('Le', 'Lateral Esquerdo'), ('La', 'Lateral Direito'), ('Go', 'Goleiro'), ('Vm', 'Segundo Volante'), ('Mc', 'Meia Central'), ('Zd', 'Zagueiro Direito'), ('Ata_e', 'Atacante Esquerda'), ('Ata_d', 'Atacante Direita')], max_length=17, null=True, verbose_name='Posicao_opcao'),
        ),
    ]
