# Generated by Django 3.1.7 on 2021-02-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20210220_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='acerto_passe_curto',
            field=models.IntegerField(default=0, verbose_name='Short_pass'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='acerto_passe_longo',
            field=models.IntegerField(default=0, verbose_name='Long_pass'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='cartao_amarelo',
            field=models.IntegerField(default=0, verbose_name='Yellow_card'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='cartao_vermelho',
            field=models.IntegerField(default=0, verbose_name='Red_card'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='cont',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='defesas',
            field=models.IntegerField(default=0, verbose_name='Defesas'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='desarmes',
            field=models.IntegerField(default=0, verbose_name='Desarmes'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='faltas',
            field=models.IntegerField(default=0, verbose_name='Faltas'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='gols',
            field=models.IntegerField(default=0, verbose_name='Gols'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='media_acert_pass_curt',
            field=models.FloatField(default=0, verbose_name='média_short_pass'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='media_acert_pass_long',
            field=models.FloatField(default=0, verbose_name='média_long_pass'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='media_cart_amar',
            field=models.FloatField(default=0, verbose_name='média_yellow_card'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='media_cart_verm',
            field=models.FloatField(default=0, verbose_name='média_red_card'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='media_defesas',
            field=models.FloatField(default=0, verbose_name='média_defesas'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='media_desarmes',
            field=models.FloatField(default=0, verbose_name='média_desarmes'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='media_faltas',
            field=models.FloatField(default=0, verbose_name='média_faltas'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='media_gols',
            field=models.FloatField(default=0, verbose_name='média_gols'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='media_pass_gol',
            field=models.FloatField(default=0, verbose_name='média_pass_gol'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='passes_gol',
            field=models.IntegerField(default=0, verbose_name='Pass_gol'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('Vm', 'Segundo Volante'), ('Le', 'Lateral Esquerdo'), ('Ze', 'Zagueiro Esquerdo'), ('Ata_d', 'Atacante Direita'), ('Ata_e', 'Atacante Esquerda'), ('Ce', 'Centroavante'), ('Zd', 'Zagueiro Direito'), ('Md', 'Meia Direita'), ('V', 'Primeiro Volante'), ('Go', 'Goleiro'), ('La', 'Lateral Direito'), ('Me', 'Meia Esquerda'), ('Mc', 'Meia Central')], default='Goleiro', max_length=17, verbose_name='Posicao'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao_opcao',
            field=models.CharField(blank=True, choices=[('Vm', 'Segundo Volante'), ('Le', 'Lateral Esquerdo'), ('Ze', 'Zagueiro Esquerdo'), ('Ata_d', 'Atacante Direita'), ('Ata_e', 'Atacante Esquerda'), ('Ce', 'Centroavante'), ('Zd', 'Zagueiro Direito'), ('Md', 'Meia Direita'), ('V', 'Primeiro Volante'), ('Go', 'Goleiro'), ('La', 'Lateral Direito'), ('Me', 'Meia Esquerda'), ('Mc', 'Meia Central')], max_length=17, null=True, verbose_name='Posicao_opcao'),
        ),
    ]
