# Generated by Django 3.1.7 on 2021-02-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20210223_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('V', 'Primeiro Volante'), ('Le', 'Lateral Esquerdo'), ('Vm', 'Segundo Volante'), ('Me', 'Meia Esquerda'), ('Mc', 'Meia Central'), ('Md', 'Meia Direita'), ('Ata_d', 'Atacante Direita'), ('Ce', 'Centroavante'), ('Go', 'Goleiro'), ('La', 'Lateral Direito'), ('Zd', 'Zagueiro Direito'), ('Ze', 'Zagueiro Esquerdo'), ('Ata_e', 'Atacante Esquerda')], default='Goleiro', max_length=17, verbose_name='Posicao'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao_opcao',
            field=models.CharField(blank=True, choices=[('V', 'Primeiro Volante'), ('Le', 'Lateral Esquerdo'), ('Vm', 'Segundo Volante'), ('Me', 'Meia Esquerda'), ('Mc', 'Meia Central'), ('Md', 'Meia Direita'), ('Ata_d', 'Atacante Direita'), ('Ce', 'Centroavante'), ('Go', 'Goleiro'), ('La', 'Lateral Direito'), ('Zd', 'Zagueiro Direito'), ('Ze', 'Zagueiro Esquerdo'), ('Ata_e', 'Atacante Esquerda')], max_length=17, null=True, verbose_name='Posicao_opcao'),
        ),
    ]
