# Generated by Django 3.1.7 on 2021-02-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_auto_20210223_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('Ce', 'Centroavante'), ('Ze', 'Zagueiro Esquerdo'), ('Md', 'Meia Direita'), ('Me', 'Meia Esquerda'), ('Mc', 'Meia Central'), ('Ata_e', 'Atacante Esquerda'), ('La', 'Lateral Direito'), ('Zd', 'Zagueiro Direito'), ('Go', 'Goleiro'), ('V', 'Primeiro Volante'), ('Ata_d', 'Atacante Direita'), ('Le', 'Lateral Esquerdo'), ('Vm', 'Segundo Volante')], default='Goleiro', max_length=17, verbose_name='Posicao'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao_opcao',
            field=models.CharField(blank=True, choices=[('Ce', 'Centroavante'), ('Ze', 'Zagueiro Esquerdo'), ('Md', 'Meia Direita'), ('Me', 'Meia Esquerda'), ('Mc', 'Meia Central'), ('Ata_e', 'Atacante Esquerda'), ('La', 'Lateral Direito'), ('Zd', 'Zagueiro Direito'), ('Go', 'Goleiro'), ('V', 'Primeiro Volante'), ('Ata_d', 'Atacante Direita'), ('Le', 'Lateral Esquerdo'), ('Vm', 'Segundo Volante')], max_length=17, null=True, verbose_name='Posicao_opcao'),
        ),
    ]
